/*
MIT License
Copyright (c) 2026 GradientTim
*/
package dev.gradienttim.gradeway.strategies

import arrow.core.Either
import arrow.core.raise.either
import dev.gradienttim.gradeway.CommonGradeway
import dev.gradienttim.gradeway.attribute.Attribute
import dev.gradienttim.gradeway.database.models.group.GroupPermissionTemplatesTable
import dev.gradienttim.gradeway.database.models.group.GroupPermissionsTable
import dev.gradienttim.gradeway.database.models.group.GroupsTable
import dev.gradienttim.gradeway.database.models.permission.DatabasePermissionEntity
import dev.gradienttim.gradeway.database.models.permission.PermissionTemplatePermissionsTable
import dev.gradienttim.gradeway.database.models.permission.PermissionTemplatesTable
import dev.gradienttim.gradeway.database.models.permission.PermissionsTable
import dev.gradienttim.gradeway.database.models.player.*
import dev.gradienttim.gradeway.database.models.role.*
import dev.gradienttim.gradeway.entity.permission.PermissionEntity
import dev.gradienttim.gradeway.extensions.limitedTo
import dev.gradienttim.gradeway.messaging.payloads.CacheFlushPayload
import dev.gradienttim.gradeway.strategy.MigrationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import net.kyori.adventure.key.Key
import org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream
import org.jetbrains.exposed.v1.core.dao.id.EntityID
import org.jetbrains.exposed.v1.jdbc.batchInsert
import org.jetbrains.exposed.v1.jdbc.deleteAll
import org.jetbrains.exposed.v1.jdbc.transactions.transaction
import java.io.File
import java.util.*

class LuckPermsMigrationStrategy(val gradeway: CommonGradeway) : MigrationStrategy {
    override val type: String = "luckperms"

    @OptIn(ExperimentalSerializationApi::class)
    override fun migrate(file: File): Either<Throwable, Unit> = either {
        GzipCompressorInputStream(file.inputStream())
            .limitedTo(gradeway.configs.config.backup.maxImportSizeBytes)
            .use { stream ->
                val data = runCatching {
                    Json.decodeFromStream<LuckPermsExport>(stream)
                }.getOrNull()

                if (data == null) {
                    raise(Throwable("Failed to decode LuckPerms data from file '${file.absolutePath}'"))
                }

                gradeway.logger.info(
                    "Migrating from LuckPerms, this may take a moment. " +
                            "(Generated by ${data.metadata.generatedBy} at ${data.metadata.generatedAt})"
                )

                if (data.tracks.isNotEmpty()) {
                    gradeway.logger.warn(
                        "Skipping ${data.tracks.size} LuckPerms track(s): Gradeway has no equivalent concept."
                    )
                }

                try {
                    transaction(gradeway.database) {
                        wipeExistingData()
                        Importer(data).run()
                    }
                } catch (throwable: Throwable) {
                    raise(throwable)
                }

                // The Importer writes directly via DAO/DSL and never publishes the fine-grained
                // payloads the services normally would, so every server's effective-permission and
                // effective-weight caches need to be dropped in full now that the migration committed.
                gradeway.messaging.publish(CacheFlushPayload)
            }
    }

    // Parent-before-child order matches CommonBackupManager's backupEntries; wiping runs it reversed so
    // every table is emptied before the tables it references.
    private fun wipeExistingData() {
        listOf(
            PermissionTemplatePermissionsTable,
            GroupPermissionTemplatesTable,
            GroupPermissionsTable,
            PlayerPermissionTemplatesTable,
            PlayerPermissionsTable,
            PlayerRolesTable,
            RolePermissionTemplatesTable,
            RolePermissionsTable,
            RoleParentsTable,
            RoleGroupsTable,
            PlayerAttributesTable,
            RoleAttributesTable,
            PlayersTable,
            RolesTable,
            PermissionTemplatesTable,
            PermissionsTable,
            GroupsTable,
        ).forEach { it.deleteAll() }
    }

    // Writes directly via DAO/DSL instead of RoleService/PlayerService/PermissionService: those services
    // each open their own transaction, linearly scan the target's existing permissions, and publish a
    // messaging event per single permission set - all pointless overhead when bulk-importing a whole
    // permission graph from scratch into tables that were just wiped.
    private inner class Importer(private val data: LuckPermsExport) {
        private val permissionIdsByValue = mutableMapOf<String, UUID>()

        @Suppress("LongMethod")
        fun run() {
            val roleEntitiesByName = data.groups.keys.associateWith { name ->
                DatabaseRoleEntity.new { this.name = name }
            }
            val roleIdsByName = roleEntitiesByName.mapValues { (_, entity) -> entity.id.value }

            val roleParents = mutableListOf<Pair<UUID, UUID>>()
            val rolePermissions = mutableListOf<Triple<UUID, UUID, Boolean>>()

            data.groups.forEach { (name, group) ->
                val roleId = roleIdsByName.getValue(name)

                processNodes(
                    nodes = group.nodes,
                    entityId = roleId,
                    entityLabel = "Role '$name'",
                    permissions = rolePermissions,
                    resolveGroupId = { groupName -> roleIdsByName[groupName] },
                    onInheritance = { parentId -> roleParents += parentId to roleId },
                    onWeight = { weight -> roleEntitiesByName.getValue(name).weight = weight },
                    addAttribute = { key, value -> addRoleAttribute(roleId, key, value) },
                )
            }

            RolePermissionsTable.batchInsert(rolePermissions) { (roleId, permissionId, enabled) ->
                this[RolePermissionsTable.roleId] = EntityID(roleId, RolesTable)
                this[RolePermissionsTable.permissionId] = EntityID(permissionId, PermissionsTable)
                this[RolePermissionsTable.isEnabled] = enabled
            }

            RoleParentsTable.batchInsert(roleParents) { (parentId, childId) ->
                this[RoleParentsTable.parentId] = EntityID(parentId, RolesTable)
                this[RoleParentsTable.childId] = EntityID(childId, RolesTable)
            }

            val playerEntitiesByName = data.users.keys.associateWith { rawId ->
                UUID.fromString(rawId).let { id ->
                    DatabasePlayerEntity.new(id) {
                        this.name = data.users.getValue(rawId).username
                    }
                }
            }
            val playerIds = playerEntitiesByName.mapValues { (_, entity) -> entity.id.value }

            val playerRoles = mutableListOf<Pair<UUID, UUID>>()
            val playerPermissions = mutableListOf<Triple<UUID, UUID, Boolean>>()

            data.users.forEach { (rawId, user) ->
                val playerId = playerIds.getValue(rawId)

                processNodes(
                    nodes = user.nodes,
                    entityId = playerId,
                    entityLabel = "Player '${user.username}'",
                    permissions = playerPermissions,
                    resolveGroupId = { groupName -> roleIdsByName[groupName] },
                    onInheritance = { roleId -> playerRoles += playerId to roleId },
                    onWeight = { weight -> playerEntitiesByName.getValue(rawId).weight = weight },
                    addAttribute = { key, value -> addPlayerAttribute(playerId, key, value) },
                )
            }

            PlayerPermissionsTable.batchInsert(playerPermissions) { (playerId, permissionId, enabled) ->
                this[PlayerPermissionsTable.playerId] = EntityID(playerId, PlayersTable)
                this[PlayerPermissionsTable.permissionId] = EntityID(permissionId, PermissionsTable)
                this[PlayerPermissionsTable.isEnabled] = enabled
            }

            PlayerRolesTable.batchInsert(playerRoles) { (playerId, roleId) ->
                this[PlayerRolesTable.playerId] = EntityID(playerId, PlayersTable)
                this[PlayerRolesTable.roleId] = EntityID(roleId, RolesTable)
            }
        }

        /**
         * Parses a LuckPerms node set for a single group or user and dispatches each node to the
         * appropriate handler, resolving prefix/suffix/weight to their highest-priority value first.
         *
         * LuckPerms allows multiple prefix/suffix/weight nodes per entity (e.g., left over from previous
         * edits); the node with the highest priority/value is the one that takes effect, so those three
         * are buffered and only emitted once the full node set has been scanned.
         *
         * @param nodes the raw LuckPerms nodes belonging to the group or user being imported
         * @param entityId the database id of the role or player these nodes belong to
         * @param entityLabel a human-readable identifier for the owning entity, used in error messages
         *   (e.g. "Role 'admin'" or "Player 'Notch'")
         * @param permissions the batch-insert buffer to append `(entityId, permissionId, enabled)` triples to
         * @param resolveGroupId resolves a group name to its role id for inheritance nodes; both groups and
         *   users inherit from LuckPerms groups, which always map to Gradeway roles
         * @param onInheritance invoked with the resolved group/role id for each inheritance node
         * @param onWeight invoked with the highest-priority weight value if any weight node was present
         * @param addAttribute invoked to persist the highest-priority display name/prefix/suffix as an attribute
         */
        @Suppress("CyclomaticComplexMethod")
        private fun processNodes(
            nodes: Set<LuckPermsExport.Node>,
            entityId: UUID,
            entityLabel: String,
            permissions: MutableList<Triple<UUID, UUID, Boolean>>,
            resolveGroupId: (String) -> UUID?,
            onInheritance: (UUID) -> Unit,
            onWeight: (Int) -> Unit,
            addAttribute: (Key, String) -> Unit,
        ) {
            var highestPrefix: PrioritizedValue? = null
            var highestSuffix: PrioritizedValue? = null
            var highestWeight: Int? = null

            nodes.forEach { node ->
                when {
                    node.isPermission -> permissions += Triple(entityId, permissionIdFor(node.key), node.value)

                    node.isInheritance -> {
                        val groupName = node.key.removePrefix(GROUP_NODE_PREFIX)
                        val groupId = resolveGroupId(groupName)
                            ?: throw IllegalStateException(
                                "$entityLabel inherits from unknown group '$groupName'"
                            )
                        onInheritance(groupId)
                    }

                    node.type == DISPLAY_NAME_NODE_TYPE ->
                        addAttribute(DISPLAY_NAME_ATTRIBUTE_KEY, node.key.removePrefix(DISPLAY_NAME_NODE_PREFIX))

                    node.type == PREFIX_NODE_TYPE -> {
                        val prefix = parsePrioritizedNode(node.key, PREFIX_NODE_PREFIX)
                        if (prefix == null) {
                            gradeway.logger.warn("Skipping malformed LuckPerms prefix node key '${node.key}'")
                        } else if (highestPrefix == null || prefix.priority > highestPrefix.priority) {
                            highestPrefix = prefix
                        }
                    }

                    node.type == SUFFIX_NODE_TYPE -> {
                        val suffix = parsePrioritizedNode(node.key, SUFFIX_NODE_PREFIX)
                        if (suffix == null) {
                            gradeway.logger.warn("Skipping malformed LuckPerms suffix node key '${node.key}'")
                        } else if (highestSuffix == null || suffix.priority > highestSuffix.priority) {
                            highestSuffix = suffix
                        }
                    }

                    node.type == WEIGHT_NODE_TYPE -> {
                        val weight = node.key.removePrefix(WEIGHT_NODE_PREFIX).toIntOrNull()
                        if (weight == null) {
                            gradeway.logger.warn("Skipping malformed LuckPerms weight node key '${node.key}'")
                        } else if (highestWeight == null || weight > highestWeight) {
                            highestWeight = weight
                        }
                    }

                    else -> gradeway.logger.warn(
                        "Skipping unsupported LuckPerms node type '${node.type}' (key '${node.key}')"
                    )
                }
            }

            highestPrefix?.let { addAttribute(PREFIX_ATTRIBUTE_KEY, it.value) }
            highestSuffix?.let { addAttribute(SUFFIX_ATTRIBUTE_KEY, it.value) }
            highestWeight?.let { onWeight(it) }
        }

        // Finds-or-creates the Permission row for a node key, deduplicating by value within this import
        // (e.g., the same wildcard granted by multiple groups) so the batched junction inserts can just
        // reference the resulting id.
        private fun permissionIdFor(nodeKey: String): UUID {
            val isWildcard = nodeKey.endsWith(WILDCARD_SUFFIX)
            val value = if (isWildcard) Regex.escape(nodeKey.removeSuffix("*")) + ".*" else nodeKey
            val permissionType = if (isWildcard) PermissionEntity.Type.REGEX else PermissionEntity.Type.EQUALS

            return permissionIdsByValue.getOrPut(value) {
                DatabasePermissionEntity.new {
                    this.value = value
                    this.type = permissionType
                }.id.value
            }
        }

        private fun addRoleAttribute(roleId: UUID, key: Key, value: String) {
            val attribute = Attribute.string(key, value)
            DatabaseRoleAttributeEntity.new {
                this.roleId = EntityID(roleId, RolesTable)
                this.type = attribute.type.type
                this.key = attribute.key
                this.value = attribute.type.serialize(attribute.value)
            }
        }

        private fun addPlayerAttribute(playerId: UUID, key: Key, value: String) {
            val attribute = Attribute.string(key, value)
            DatabasePlayerAttributeEntity.new {
                this.playerId = EntityID(playerId, PlayersTable)
                this.type = attribute.type.type
                this.key = attribute.key
                this.value = attribute.type.serialize(attribute.value)
            }
        }

        // LuckPerms encodes the priority in the node key itself, e.g. "prefix.10.Test" -> priority 10,
        // value "Test". The value may itself contain dots, so only the first two segments are split off.
        private fun parsePrioritizedNode(key: String, nodePrefix: String): PrioritizedValue? {
            val remainder = key.removePrefix(nodePrefix)
            val separatorIndex = remainder.indexOf('.')
            if (separatorIndex == -1) return null

            val priority = remainder.substring(0, separatorIndex).toIntOrNull() ?: return null
            return PrioritizedValue(priority, remainder.substring(separatorIndex + 1))
        }
    }

    private data class PrioritizedValue(
        val priority: Int,
        val value: String
    )

    @Serializable
    private data class LuckPermsExport(
        val metadata: Metadata,
        val groups: Map<String, Group>,
        val tracks: Map<String, Track>,
        val users: Map<String, User>
    ) {
        @Serializable
        data class Metadata(
            val generatedBy: String,
            val generatedAt: String
        )

        @Serializable
        data class Group(
            val nodes: Set<Node>
        )

        @Serializable
        data class Track(
            val groups: Set<String>
        )

        @Serializable
        data class User(
            val username: String,
            val nodes: Set<Node>
        )

        @Serializable
        data class Node(
            val type: String,
            val key: String,
            val value: Boolean
        ) {
            val isPermission: Boolean
                get() = type == "permission"

            val isInheritance: Boolean
                get() = type == "inheritance"
        }
    }

    private companion object {
        const val WILDCARD_SUFFIX = ".*"
        const val GROUP_NODE_PREFIX = "group."
        const val DISPLAY_NAME_NODE_TYPE = "display_name"
        const val DISPLAY_NAME_NODE_PREFIX = "displayname."

        val DISPLAY_NAME_ATTRIBUTE_KEY: Key = Key.key("gradeway", "display_name")
        val PREFIX_ATTRIBUTE_KEY: Key = Key.key("gradeway", "prefix")
        val SUFFIX_ATTRIBUTE_KEY: Key = Key.key("gradeway", "suffix")

        const val PREFIX_NODE_TYPE = "prefix"
        const val SUFFIX_NODE_TYPE = "suffix"
        const val WEIGHT_NODE_TYPE = "weight"

        const val PREFIX_NODE_PREFIX = "prefix."
        const val SUFFIX_NODE_PREFIX = "suffix."
        const val WEIGHT_NODE_PREFIX = "weight."
    }
}
